### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by strowk** [phrase/phrase-go#8]
Today when I run `phrase pull`  it gave me following error:

```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                      
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e029c]

goroutine 1 [running]:
github.com/phrase/phrase-cli/cmd/internal.LocalesForProjects(0xc000123540, 0xb6e520, 0xc0002476e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/phrase/phrase-cli/cmd/internal/shared.go:38 +0x1bc
github.com/phrase/phrase-cli/cmd/internal.(*PullCommand).Run(0xc00018fcb8, 0xc0002964e0, 0x15, 0x0)
        /go/src/github.com/phrase/phrase-cli/cmd/internal/pull.go:55 +0x21f
github.com/phrase/phrase-cli/cmd.initPull.func1(0xc000287600, 0xc0002785e0, 0x0, 0x2)
        /go/src/github.com/phrase/phrase-cli/cmd/pull.go:24 +0xef
github.com/spf13/cobra.(*Command).execute(0xc000287600, 0xc0002785c0, 0x2, 0x2, 0xc000287600, 0xc0002785c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xe22ca0, 0x41aa01, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/phrase/phrase-cli/cmd.Execute()
        /go/src/github.com/phrase/phrase-cli/cmd/root.go:64 +0x2d
main.main()
        /go/src/github.com/phrase/phrase-cli/main.go:8 +0x25
```

**Comment by theSoenke** [comment]
Hey @strowk, could you try it again with the latest version of the CLI? This should be fixed now

**Comment by forelabs** [comment]
Closed due to inactivity
